src/recipe_project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import login_view, logout_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls', namespace='recipes')),
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/recipes/urls.py
from django.urls import path
from .views import home, RecipeListView, RecipeDetailView, recipe_search, recipe_analytics, add_recipe, RecipeUpdateView, RecipeDeleteView, about_page

app_name = 'recipes'

urlpatterns = [
  path('', home, name='home'),
  path('list/', RecipeListView.as_view(), name='list'),
  path('list/<pk>', RecipeDetailView.as_view(), name='detail'),
  path('search/', recipe_search, name='search'),
  path('analytics/', recipe_analytics, name='analytics'),
  path('add/', add_recipe, name='add'),
  path('update/<pk>', RecipeUpdateView.as_view(), name='update'),
  path('delete/<pk>', RecipeDeleteView.as_view(), name='delete'),
  path('about', about_page, name='about'),
]

src/recipes/models.py
from django.db import models
from django.shortcuts import reverse

class Recipe(models.Model):
  name= models.CharField(max_length=50)
  ingredients= models.CharField(max_length=500, help_text="Separate each ingredient with comma")
  cooking_time= models.PositiveIntegerField(help_text="Cooking time in minutes")
  difficulty= models.CharField(max_length=20, editable=False, null=True, blank=True) 
  description= models.TextField()
  pic = models.ImageField(upload_to='recipes', default='no_picture.jpg')

  def calculate_difficulty(self):
    num_ingredients = len(self.ingredients.split(','))

    if self.cooking_time < 10 and num_ingredients <= 4:
        self.difficulty = 'Easy'
    elif self.cooking_time < 10 and num_ingredients >= 4:
        self.difficulty = 'Medium' 
    elif self.cooking_time >= 10 and num_ingredients < 4:
        self.difficulty = 'Intermediate'
    else:
        self.difficulty = 'Hard'

  def save(self, *args, **kwargs):
        self.calculate_difficulty()
        super().save(*args, **kwargs)

  def __str__(self):
    return str(self.name)

  def get_absolute_url(self):
    return reverse ('recipes:detail', kwargs={'pk': self.pk})

src/recipes/forms.py
from django import forms
from .models import Recipe

class RecipeSearchForm(forms.Form): 
    DIFFICULTY_CHOICES = [
        ('', 'All'),
        ('Easy', 'Easy'),
        ('Medium', 'Medium'),
        ('Intermediate', 'Intermediate'),
        ('Hard', 'Hard'),
    ]

    name = forms.CharField(
        required=False,
        label="Recipe Name",
        widget=forms.TextInput(attrs={'placeholder': 'Enter recipe name'})
    )
    difficulty = forms.ChoiceField(
        required=False,
        choices=DIFFICULTY_CHOICES,
        label="Difficulty",
    )
    ingredient = forms.CharField(
        required=False,
        max_length=120,
        label='Ingredient',
        widget=forms.TextInput(attrs={'placeholder': 'Enter desired ingredient'})
    )

class RecipeForm(forms.ModelForm):
    class Meta:
        model = Recipe
        fields = ['name', 'ingredients', 'cooking_time', 'description', 'pic']
        widgets = {
            'ingredients': forms.Textarea(attrs={'rows': 3}),
            'description': forms.Textarea(attrs={'rows': 5, 'placeholder': 'Enter recipe description'}),
        }
        labels = {
            'pic': 'Recipe Image',
        }

    def clean(self):
        cleaned_data = super().clean()

        name = cleaned_data.get('name')
        if name:
            cleaned_data['name'] = name.capitalize()

        ingredients = cleaned_data.get('ingredients')
        if ingredients:
            ingredients_list = [ingredient.strip().capitalize() for ingredient in ingredients.split(',')]
            cleaned_data['ingredients'] = ', '.join(ingredients_list)

        return cleaned_data

src/recipes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, UpdateView, DeleteView  
from .models import Recipe
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from .forms import RecipeSearchForm, RecipeForm
from .utils import generate_charts
import pandas as pd

def home(request):
  return render(request, 'recipes/recipes_home.html')

class RecipeListView(LoginRequiredMixin, ListView):
  model = Recipe
  template_name = 'recipes/recipe_list.html'

class RecipeDetailView(LoginRequiredMixin, DetailView):
  model = Recipe
  template_name = 'recipes/recipe_detail.html'

class RecipeUpdateView(LoginRequiredMixin, UpdateView):
  model = Recipe
  fields = ['name', 'ingredients', 'cooking_time', 'description', 'pic']
  template_name = 'recipes/recipe_update.html'

  def form_valid(self, form):
        name = form.cleaned_data.get('name')
        if name:
            form.instance.name = name.capitalize()

        ingredients = form.cleaned_data.get('ingredients')
        if ingredients:
            ingredients_list = [ingredient.strip().capitalize() for ingredient in ingredients.split(',')]
            form.instance.ingredients = ', '.join(ingredients_list)

        return super().form_valid(form)

class RecipeDeleteView(LoginRequiredMixin, DeleteView):
  model = Recipe
  template_name = 'recipes/recipe_delete.html'

  def get_success_url(self):
    return ('/list/')
  
@login_required
def add_recipe(request):
    if request.method == 'POST':
        form = RecipeForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('recipes:list')  
    else:
        form = RecipeForm()
    
    context = {
        'form': form,
    }
    return render(request, 'recipes/add_recipe.html', context)

@login_required
def recipe_search(request):
    form = RecipeSearchForm(request.GET or None)
    recipes = Recipe.objects.all()

    # Filter recipes based on search criteria
    if form.is_valid():
        name = form.cleaned_data.get('name', '')
        difficulty = form.cleaned_data.get('difficulty', '')
        ingredient = form.cleaned_data.get('ingredient', '')

        if name:
            recipes = recipes.filter(name__icontains=name)
        if difficulty:
            recipes = recipes.filter(difficulty=difficulty)
        if ingredient:
            recipes = recipes.filter(ingredients__icontains=ingredient)
        

    # Convert QuerySet to pandas DataFrame
    recipe_df = pd.DataFrame.from_records(
       recipes.values('id', 'name', 'difficulty', 'cooking_time'))

    context = {
        'form': form,
        'recipe_df': recipe_df,
        'recipes': recipes,
    }
    return render(request, 'recipes/recipe_search.html', context)

@login_required
def recipe_analytics(request):
    # Fetch recipes from the database
    recipes = Recipe.objects.all()

    # Extract data
    recipe_names = [recipe.name for recipe in recipes]
    cooking_times = [recipe.cooking_time for recipe in recipes]
    difficulties = [recipe.difficulty for recipe in recipes]
    ingredient_counts = [len(recipe.ingredients.split(',')) for recipe in recipes]  

    # Create a dictionary for difficulties
    difficulty_counts = {difficulty: difficulties.count(difficulty) for difficulty in set(difficulties)}

    # Generate charts
    charts = generate_charts(recipe_names, cooking_times, difficulty_counts, ingredient_counts)

    return render(request, 'recipes/recipe_analytics.html', {'charts': charts})

@login_required
def about_page(request):
   return render(request, 'recipes/about.html')

src/recipes/templates/recipes/about.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}About{% endblock %}

{% block content %}
<div class="hero-image">
  <br />
  <div class="about-container">
    <h1 class="main-header">About Me</h1>

    <p>
      I'm a full-stack web developer based in the UK. I enjoy creating
      functional and engaging websites and apps.
    </p>
    <h3 class="contact-header">Check out some of my code!</h3>
    <div class="contact-links">
      <div>
        <a
          href="https://c1904h.github.io/portfolio-website/index.html"
          target="_blank"
          >View My Portfolio</a
        >
      </div>
      <h4>Find me on:</h4>
      <div>
        <a
          href="https://github.com/C1904H"
          target="_blank"
          >Github</a
        >
      </div>
      <div>
        <a
          href="https://www.linkedin.com/in/corinne-haggerty-2b98706b/"
          target="_blank"
          >LinkedIn</a
        >
      </div>
      <p class="email-link"><a href="mailto:C1904H@aol.com">Email Me</a></p>
   </div>
  </div>
</div>
{% endblock content %}

src/recipes/templates/recipes/add_recipe.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}Add Recipe{% endblock %} 

{% block content %}
<div class="template-image">

  <div class="add_recipe-container">
      <h1>Add a New Recipe</h1>
      <form class="add_recipe-form" method="POST" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary" onclick="return alert('Recipe Successfully Added!');">Add Recipe</button>
      </form>
  </div>

</div>
{% endblock content %}

src/recipes/templates/recipes/recipe_analytics.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}Recipe Analytics{% endblock %} 

{% block content %}
<div class="template-image">
  

  <div class="analytics">
      <h1 class="main-header" style="font-size: 50px">Recipe Analytics</h1>
    <div class="chart-container">
      <div class="chart-item">
      <h2>Cooking Time Per Recipe</h2>
      <img class="bar_chart" src="data:image/png;base64,{{ charts.bar_chart }}" alt="Bar Chart">
    </div>
    <div class="chart-item">
      <h2>Number of Ingredients Per Recipe</h2>
      <img class="line_chart" src="data:image/png;base64,{{ charts.line_chart_ingredients }}" alt="Line Chart - Ingredients">
    </div>
      <div class="chart-item">
      <h2>Recipe Difficulty Distribution</h2>
      <img class="pie_chart" src="data:image/png;base64,{{ charts.pie_chart }}" alt="Pie Chart">
    </div>
    </div>     
</div>
</div>
{% endblock content %}

src/recipes/templates/recipes/recipe_delete.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}Delete Recipe{% endblock %} 

{% block content %}
<div class="template-image">
<br/>

<div class="add_recipe-container">
    <h1>Delete Recipe</h1>
    <p style="text-align: center;">Are you sure you want to delete the recipe <span class="recipe-delete">{{ object.name }}</span> ?</p>
    <form method="POST">
        {% csrf_token %}
        <div class="button-container">
        <button type="submit" class="btn btn-danger" onclick="return alert('Recipe Successfully Deleted!');" >Yes, Delete</button>
        <a href="{% url 'recipes:detail' object.pk %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>
</div>
{% endblock %}

src/recipes/templates/recipes/recipe_detail.html
{% extends "base.html" %} 
{% load static %} 

{% block title %}{{object.name}}Recipe {% endblock %} 

{% block content %}
<div class="template-image">
  
  <br />
  <br />
  <div class="detail-box">
    <h1 class="recipe-name">{{object.name}}</h1>

    <img
      src="{{object.pic.url}}"
      class="recipe-image-detail"
    /><br />
    <b class="recipe-detail">Details: </b> {{object.description|safe}} 
    <b class="recipe-ingredients">Ingredients: </b> {{object.ingredients}} <br />
    <p><b class="recipe-time">Cooking Time: </b>{{object.cooking_time}} mins &nbsp; <b class="recipe-diff">Difficulty:</b> {{object.difficulty}}<br /></p>
    <br/>
    <div clas="button-container">
    <a href="{% url 'recipes:update' object.pk %}" class="btn btn-primary">Edit Recipe</a>
    <!-- <a href="{% url 'recipes:delete' object.pk %}" class="btn btn-danger">Delete Recipe</a> -->
  </div>
</div>
</div>
{% endblock content %}

src/recipes/templates/recipes/recipe_list.html
{% extends "base.html" %} 
{% load static %} 
{% load recipe_tags %}

{% block title %} Recipes List {%endblock %} 

  {% block content %}
  
  <!-- <div class="recipe-container"> -->
    <div class="template-image">
  <h1
    class="main-header"
    style="font-size: 40px"
  >
    Recipes
  </h1>
  <div class="recipe-grid">
    {% for object in object_list %}
    <div class="recipes-container">
      <a
        href="{{object.get_absolute_url}}"
        class="recipe-wrapper"
      >
        <div>
          <img
            src="{{object.pic.url}}"
            class="recipe-image"
            width="200"
            height="200"
          />
        </div>
        <div>
          <h2 class="recipe-name">{{object.name}}</h2>
          <p class="recipe-description">{{object.description|short_description|safe}}</p>
          <p class="recipe-cooking_time">Cooking Time: {{object.cooking_time}} mins<br />
           Difficulty: {{object.difficulty}}</p>
        </div>
      </a>
    </div> 
    {% endfor %}
  </div>
</div>
{% endblock content %}

src/recipes/templates/recipes/recipe_search.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}Recipe Search{% endblock %} 

{% block content %}
<div class="template-image">

  <div class="search-page">
      <h1 class="main-header" style="font-size: 50px">Recipe Search</h1>
      <div class="search-box">
      <h2>Search for a recipe using one or more of the following options:</h2>
      <!-- Search Form -->
      <form method="GET" action="">
          {{ form.as_p }}
          <button type="submit" class="login-button">Search</button> <br/>
          <br/>
          <a href="{% url 'recipes:list' %}" style="color: #e25d46; font-weight: 700">Show All Recipes</a>
      </form>
    </div>
    <br/>
      <hr>
      
      <!-- Results Table -->
      <h2 style="text-align: center;">Search Results</h2>
      <!-- <div>
          {{ recipe_df|safe }}
      </div> -->
      {% if recipes %}
      <table class="search-results-table">
        <thead>
          <tr>
            <th>Recipe</th>
            <th>Difficulty</th>
            <th>Cooking Time (mins)</th>
          </tr>
        </thead>
        <tbody>
          {% for recipe in recipes %}
            <tr>
              <td><a href="{{recipe.get_absolute_url}}" style="color: #e25d46">{{recipe.name}}</a></td>
              <td>{{recipe.difficulty}}</td>
              <td>{{recipe.cooking_time}}</td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    {% else %}
      <p>No recipes found matching your search criteria.</p>
    {% endif %}
  </div>
  </div>
{% endblock content %}

src/recipes/templates/recipes/recipe_update.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}Recipe Update{% endblock %} 

{% block content %}
<div class="template-image">
<br/>

<div class="add_recipe-container">
    <h1>Edit Recipe</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="button-container">
        <button type="submit" class="btn btn-success" onclick="return alert('Recipe Successfully Updated!');" >Save Changes</button>
        <a href="{% url 'recipes:detail' object.pk %}" class="btn btn-secondary">Cancel</a>
      </div>
    </form>
</div>
</div>
{% endblock %}

src/recipes/templates/recipes/recipes_home.html
{% extends "base.html" %} 
{% load static %} 
{% block title %}Recipes Home{% endblock %} 

{% block content %} 
<div class="hero-image"> 
  <div class="hero-text">
    
    <h1
      class="main-header"
      style="font-size: 50px"
    >
      Welcome to the Recipe App!
    </h1>
    <h2>Login to access features:</h2>
    <div class="features-container">
      <div class="feature-item">
        <a class="feature-title" href="{%url 'recipes:list' %}" style="color: #e25d46">Recipe List</a>
      <img src="{% static 'recipes/images/list.png' %}" alt="image of recipe list page">
    </div>
      <div class="feature-item">
        <div class="feature-title">Recipe Detail</div>
      <img src="{% static 'recipes/images/detail.png' %}" alt="image of recipe detail page">
    </div>
      <div class="feature-item">
        <a class="feature-title" href="{%url 'recipes:search' %}" style="color: #e25d46">Recipe Search</a>
      <img src="{% static 'recipes/images/search.png' %}" alt="image of recipe search page">
    </div>
      <div class="feature-item">
        <a class="feature-title" href="{%url 'recipes:analytics' %}" style="color: #e25d46">Recipe Analytics</a>
      <img src="{% static 'recipes/images/analytics.png' %}" alt="image of recipe analytics page">
    </div>
    </div>
    <a
      href="{%url 'login' %}"
      class="login-button"
      >Login</a
    >
  </div>
</div>

{% endblock content %}